 var support = {
  categories: [
      ["VietNam", "vietnam-food.png"],
      ["American", "american-food.jpg"],
      ["Chinese", "chinese-food.jpg"],
      ["Mexican", "mexican-food.jpg"],
      ["Indian", "Indian-food.jpg"],
      ["Spanish", "spanish-food.jpg"],
  ], 
  dateCategories() {
    let listCategories = this.categories.map((category) => {
      return {
        name: category[0],
        image: category[1],
      };
    });
    return listCategories;
  },

  getNameCategories() {
    return this.categories.map((category) => category[0]);
  },

  dataRecipes() {
    const recipes = [
      [
        "Pho",
        "A simple yet an incredible dish, Pho (pronounced as 'fuh') is a Vietnamese dish made of rice noodles and meat (usually beef or chicken) served in broth and topped with herbs. The dish has got a great fragrance which lingers in the eater's head for a while. A popular street food item, Pho is flavourful yet balanced in nature. A perfect dish to have on a winter evening. You and this dish are certainly made 'pho' each other.",
        "vietnam@food.co.vn",
        [
          " 1.5 kg beef bone",
          "200g beef fillet",
          "500g beef balls",
          "Rice noodle",
          "Red onion, green onion, onion",
          "Lemon, ginger",
          "Cloves, star anise, cardamom, cinnamon or pho seasoning",
        ],
        "VietNam",
        "pho.jpg",
      ],
      [
        "Banh Mi",
        "Banh Mi is a Vietnamese sandwich made with crispy bread and filled with a variety of savory ingredients, such as pork belly, grilled pork, or chicken. The sandwich is typically dressed with pickled vegetables, cilantro, and spicy chili sauce, giving it a perfect balance of flavors and textures. Banh Mi is a popular street food in Vietnam and a must-try for anyone visiting the country.",
        "vietnam@food.co.vn",
        [
          "1 baguette",
          "200g pork belly",
          "Pickled carrots and daikon",
          "Cilantro",
          "Mayonnaise",
          "Sriracha sauce",
        ],
        "VietNam",
        "banh-mi.jpg",
      ],
      [
        "Vietnamese Bun Cha",
        "Bun Cha is a Vietnamese dish of grilled pork meatballs and rice noodles served with a tangy dipping sauce and fresh herbs. It's a popular street food in Vietnam, and a perfect light yet flavorful meal. The combination of smoky grilled meat and cool, refreshing herbs and vegetables makes Bun Cha a great choice for a hot summer day.",
        "vietnam@food.co.vn",
        [
          "500g ground pork",
          "2 tbsp fish sauce",
          "1 tbsp soy sauce",
          "1 tbsp sugar",
          "1 tbsp vegetable oil",
          "1 tsp salt",
          "1 tsp black pepper",
          "1/2 tsp garlic powder",
          "1/2 tsp onion powder",
          "1/4 cup chopped scallions",
          "1/4 cup chopped cilantro",
          "1/4 cup chopped mint",
          "1/4 cup chopped basil",
          "1/4 cup chopped lettuce",
          "1/4 cup chopped cucumber",
          "1/4 cup chopped carrot",
          "1/4 cup chopped daikon",
          "1/4 cup chopped pickled vegetables",
          "1/4 cup roasted peanuts",
          "1/4 cup fried shallots",
          "Rice noodles",
        ],
        "VietNam",
        "bun_cha.jpg",
      ],
      [
        "Banh Xeo",
        "Banh Xeo is a Vietnamese savory pancake made with rice flour, turmeric, and coconut milk. The pancake is filled with shrimp, pork, bean sprouts, and scallions and is served with lettuce leaves and herbs for wrapping. Banh Xeo is a popular street food in Vietnam and is perfect for a light and satisfying meal.",
        "vietnam@food.co.vn",
        [
          "1 cup rice flour",
          "1/2 cup cornstarch",
          "1 teaspoon turmeric powder",
          "1 cup coconut milk",
          "1/2 lb pork belly",
          "1/2 lb shrimp",
          "Bean sprouts",
          "Scallions",
          "Lettuce leaves",
          "Mint and cilantro leaves",
          "Fish sauce",
          "Chili peppers",
        ],
        "VietNam",
        "banh-xeo.jpg",
      ],
      [
        "Bánh cuốn",
        "A popular dish in Vietnam, Bánh cuốn is a type of steamed rice noodle roll that is typically filled with seasoned ground pork and minced mushrooms, and then topped with crispy fried onions. It is often served with a dipping sauce made with fish sauce, vinegar, sugar, and chili peppers. Bánh cuốn is a common breakfast dish in Vietnam and is also enjoyed as a snack or light meal throughout the day.",
        "vietnam@food.co.vn",
        [
          "1 cup rice flour",
          "1/4 cup tapioca flour",
          "2 cups water",
          "1/4 teaspoon salt",
          "1/4 teaspoon sugar",
          "1/4 teaspoon turmeric powder",
          "Ground pork",
          "Minced mushrooms",
          "Fried onions for topping",
          "Fish sauce, vinegar, sugar, and chili peppers for dipping sauce",
        ],
        "VietNam",
        "banhcuon.jpg",
      ],
      [
        "Gỏi cuốn",
        "Gỏi cuốn, also known as Vietnamese spring rolls, are a fresh and healthy appetizer or snack that are typically filled with vermicelli noodles, shrimp, pork, lettuce, and herbs such as mint and cilantro. They are wrapped in rice paper and served with a peanut dipping sauce. Gỏi cuốn are a popular dish in Vietnam and are also enjoyed in other parts of Southeast Asia.",
        "vietnam@food.co.vn",
        [
          "Rice paper wrappers",
          "Vermicelli noodles",
          "Shrimp",
          "Pork",
          "Lettuce",
          "Mint leaves",
          "Cilantro",
          "Peanuts for the dipping sauce",
          "Fish sauce, hoisin sauce, and sugar for the dipping sauce",
        ],
        "VietNam",
        "goicuon.jpg",
      ],
      [
        "Bún thịt nướng",
        "Bún thịt nướng is a popular Vietnamese dish that consists of grilled pork served over a bed of vermicelli noodles, lettuce, cucumber, and herbs such as mint and cilantro. It is typically dressed with fish sauce, sugar, vinegar, and chili peppers. Bún thịt nướng is a refreshing and flavorful dish that is enjoyed as a light meal or as a main course.",
        "vietnam@food.co.vn",
        [
          "Grilled pork",
          "Vermicelli noodles",
          "Lettuce",
          "Cucumber",
          "Mint leaves",
          "Cilantro",
          "Fish sauce",
          "Sugar",
          "Vinegar",
          "Chili peppers",
        ],
        "VietNam",
        "bunthitnuong.jpg",
      ],
      [
        "Hamburger",
        "A classic American dish, a hamburger is made of a cooked ground beef patty served between two pieces of a sliced bun. The meat is seasoned with salt and pepper and can be topped with a variety of toppings like cheese, lettuce, tomatoes, pickles, onions, ketchup, mustard, and mayonnaise. It is a popular fast food item that is also enjoyed at cookouts, restaurants, and diners. A juicy hamburger can satisfy your hunger pangs and leave you feeling satisfied.",
        "American@food.co.vn",
        [
          "500g ground beef",
          "4 hamburger buns",
          "4 slices of cheese",
          "1 tomato",
          "1 onion",
          "Lettuce",
          "Ketchup, mustard, and mayonnaise",
          "Salt and pepper",
        ],
        "American",
        "hamburger.jpg",
      ],
      [
        "Apple Pie",
        "An iconic American dessert, apple pie is a sweet dish made of apples baked in a pastry crust. The filling is made of thinly sliced apples mixed with sugar, cinnamon, nutmeg, and lemon juice, while the crust can be made of shortcrust, puff pastry, or a combination of both. Apple pie is often served with whipped cream or vanilla ice cream, making it a perfect ending to a delicious meal.",
        "American@food.co.vn",
        [
          "6 apples",
          "1/2 cup of sugar",
          "1/2 teaspoon of cinnamon",
          "1/4 teaspoon of nutmeg",
          "1 tablespoon of lemon juice",
          "1 pie crust",
          "1/4 cup of flour",
          "2 tablespoons of butter",
        ],
        "American",
        "apple_pie.jpg",
      ],
      [
        "Barbecue Ribs",
        "Barbecue ribs are a popular American dish made by cooking pork or beef ribs in a sauce made of spices, vinegar, and tomato sauce. The ribs are typically cooked on a grill or in the oven until they are tender and falling off the bone. Barbecue ribs are often served with a side of coleslaw, cornbread, or baked beans, and are a staple of summer barbecues and cookouts in the United States.",
        "us@food.co.vn",
        [
          "Pork or beef ribs",
          "Spices",
          "Vinegar",
          "Tomato sauce",
          "Coleslaw",
          "Cornbread",
          "Baked beans",
        ],
        "American",
        "barbecue-ribs.jpg",
      ],
      [
        "Mac and Cheese",
        "Mac and cheese is a classic American comfort food made by combining cooked macaroni noodles with a cheese sauce made from cheddar cheese, milk, and butter. The dish is typically baked in the oven until the top is crispy and golden brown. Mac and cheese is a popular side dish and is also served as a main course, often with additional ingredients such as bacon, breadcrumbs, or vegetables.",
        "us@food.co.vn",
        [
          "Macaroni noodles",
          "Cheddar cheese",
          "Milk",
          "Butter",
          "Bacon",
          "Breadcrumbs",
          "Vegetables",
        ],
        "American",
        "mac-and-cheese.jpg",
      ],
      [
        "Fried Chicken",
        "Fried chicken is a popular American dish made by coating chicken in a seasoned flour mixture and then frying it until it is crispy and golden brown. The dish is often served with a side of mashed potatoes, gravy, and corn. Fried chicken is a classic comfort food in the United States and is a staple of southern cuisine.",
        "us@food.co.vn",
        ["Chicken", "Flour", "Seasonings", "Mashed potatoes", "Gravy", "Corn"],
        "American",
        "fried-chicken.jpg",
      ],
      [
        "Dim Sum",
        "A popular Cantonese dish, Dim Sum is a collection of small bite-sized portions of food served in small steamer baskets or on small plates. Dim Sum items vary from savory to sweet and can include dishes like dumplings, buns, rice noodle rolls, and desserts. It is typically served with tea and is a staple of Cantonese cuisine.",
        "Chinese@food.co.vn",
        [
          "Dumplings",
          "Buns",
          "Rice noodle rolls",
          "Steamed vegetables",
          "Egg tarts",
          "Sweet sesame balls",
        ],
        "Chinese",
        "dim-sum.jpg",
      ],

      [
        "Hot Pot",
        "A popular Chinese dish, Hot Pot is a communal dining experience where diners cook a variety of meats, seafood, and vegetables in a simmering pot of broth at the center of the table. The broth is typically flavored with spices and herbs and the ingredients are dipped in a dipping sauce before eating. It is enjoyed with family and friends.",
        "Chinese@food.co.vn",
        [
          "Thinly sliced meat (beef, lamb, pork, or chicken)",
          "Fish or seafood",
          "Tofu",
          "Mushrooms",
          "Dipping sauce (usually sesame sauce or peanut sauce)",
        ],
        "Chinese",
        "hot-pot.jpg",
      ],
      [
        "Fried Rice",
        "A staple dish in Chinese cuisine, fried rice is a simple yet delicious dish made of steamed rice stir-fried with vegetables, eggs, and meat. The dish can be customized according to one's taste by adding a variety of ingredients like shrimp, chicken, pork, peas, carrots, onions, and soy sauce. It is a quick and easy meal that can be enjoyed at any time of the day and is often served as a side dish or main course in Chinese restaurants.",
        "Chinese@food.co.vn",
        [
          "2 cups of cooked rice",
          "1 cup of mixed vegetables (carrots, peas, corn)",
          "2 eggs",
          "1 cup of cooked shrimp, chicken, or pork (optional)",
          "Soy sauce",
          "Salt and pepper",
          "Oil",
        ],
        "Chinese",
        "fried-rice.jpg",
      ],
      [
        "Gong Bao Chicken",
        "Gong Bao Chicken, also known as Kung Pao Chicken, is a spicy Sichuan dish made with diced chicken, peanuts, vegetables, and chili peppers. The dish is stir-fried and then coated in a savory sauce made with soy sauce, vinegar, and sugar. It is a popular dish in China and is enjoyed both as a main course and as a side dish.",
        "chinacuisine@food.co.cn",
        [
          "Chicken",
          "Peanuts",
          "Vegetables",
          "Chili peppers",
          "Soy sauce",
          "Vinegar",
          "Sugar",
        ],
        "Chinese",
        "gongbaochicken.jpg",
      ],
      [
        "Ma Po Tofu",
        "Ma Po Tofu is a spicy and flavorful dish made with soft tofu, ground pork, chili bean sauce, and Sichuan peppercorns. It is a popular dish in Sichuan cuisine and is known for its numbing and spicy flavors. The dish is typically served with steamed rice and is enjoyed as a main course.",
        "chinacuisine@food.co.cn",
        ["Tofu", "Ground pork", "Chili bean sauce", "Sichuan peppercorns"],
        "Chinese",
        "mapotofu.jpg",
      ],
      [
        "Zhajiangmian",
        "Zhajiangmian, also known as fried sauce noodles, is a popular dish in northern China made with wheat noodles and a savory sauce made with fermented soybeans, ground pork, and vegetables. The sauce is stir-fried with the noodles and is often served with cucumber and bean sprouts on top. It is a filling and satisfying dish that is enjoyed as a main course.",
        "chinacuisine@food.co.cn",
        ["Wheat noodles", "Fermented soybeans", "Ground pork", "Vegetables"],
        "Chinese",
        "zhajiangmian.jpg",
      ],
      [
        "Tacos al Pastor",
        "Tacos al Pastor is a popular Mexican dish made with marinated pork, pineapple, onions, and cilantro served on a small tortilla. The pork is typically cooked on a vertical spit with pineapple on top, creating layers of juicy, flavorful meat. This dish is a favorite among locals and tourists alike and can be found at street vendors, taquerias, and restaurants throughout Mexican.",
        "Mexican@food.co.vn",
        [
          "1 lb pork shoulder",
          "1/2 cup pineapple juice",
          "2 garlic cloves, minced",
          "1/2 tsp oregano",
          "1/2 tsp cumin",
          "1/2 tsp paprika",
          "1/4 tsp cinnamon",
          "1/4 tsp cayenne pepper",
          "1/4 tsp salt",
          "1/4 tsp black pepper",
          "1/2 onion, chopped",
          "1/2 cup chopped pineapple",
          "Tortillas",
          "Cilantro and onions for topping",
        ],
        "Mexican",
        "tacos-al-pastor.jpg",
      ],
      [
        "Chiles Rellenos",
        "Chiles Rellenos is a classic Mexican dish consisting of stuffed and battered poblano peppers. The peppers are usually stuffed with cheese or meat and then coated in egg batter and fried. They are served with tomato sauce or salsa on top and often accompanied by rice, beans, or a salad. This dish is a favorite in many Mexican households and is also popular in Mexican restaurants.",
        "Mexican@food.co.vn",
        [
          "6 poblano peppers",
          "1 lb ground beef",
          "1/2 onion, chopped",
          "2 garlic cloves, minced",
          "1 tsp ground cumin",
          "1 tsp dried oregano",
          "1/2 tsp salt",
          "1/4 tsp black pepper",
          "1 cup shredded cheese",
          "1/2 cup flour",
          "3 eggs, separated",
          "1/2 cup vegetable oil",
          "Tomato sauce or salsa for topping",
        ],
        "Mexican",
        "chiles-rellenos.jpg",
      ],
      [
        "Guacamole",
        "Guacamole is a popular Mexican dip made from mashed avocado, lime juice, cilantro, and various seasonings such as garlic, onion, and chili peppers. It is commonly served with tortilla chips as an appetizer or used as a condiment for tacos, burritos, and other Mexican dishes. Guacamole is a rich and creamy dip that is both healthy and delicious.",
        "mexico@food.co.mx",
        [
          "Avocado",
          "Lime juice",
          "Cilantro",
          "Garlic",
          "Onion",
          "Chili peppers",
          "Salt",
        ],
        "Mexican",
        "guacamole.jpg",
      ],
      [
        "Enchiladas",
        "Enchiladas are a popular Mexican dish that consists of tortillas rolled around a filling of meat, cheese, beans, or vegetables, and covered with a chili pepper sauce. The enchiladas are typically baked until the tortillas are crispy and the filling is hot and bubbly. Enchiladas are a flavorful and satisfying dish that is enjoyed as a main course.",
        "mexico@food.co.mx",
        [
          "Tortillas",
          "Meat",
          "Cheese",
          "Beans",
          "Chili pepper sauce",
          "Onion",
          "Garlic",
          "Cumin",
        ],
        "Mexican",
        "enchiladas.jpg",
      ],
      [
        "Pico de Gallo",
        "Pico de Gallo is a fresh and chunky salsa that is a popular condiment in Mexican cuisine. It is made from diced tomatoes, onions, jalapeño peppers, cilantro, and lime juice. Pico de Gallo is typically served as a topping for tacos, burritos, and other Mexican dishes, and is also delicious as a dip with tortilla chips. It is a healthy and flavorful way to add a kick of flavor to any dish.",
        "mexico@food.co.mx",
        [
          "Tomatoes",
          "Onions",
          "Jalapeño peppers",
          "Cilantro",
          "Lime juice",
          "Salt",
        ],
        "Mexican",
        "picodegallo.jpg",
      ],

      [
        "Biryani",
        "A fragrant rice dish, Biryani is a popular Indian dish made with basmati rice and meat (usually chicken or lamb) that is cooked in a mix of spices, herbs, and yogurt. The dish is typically garnished with fried onions and cashews, and is often served with raita, a side dish made with yogurt and vegetables. Biryani is a special occasion dish and is a staple at weddings and festivals throughout Indian.",
        "Indian@food.co.vn",
        [
          "1 kg chicken or lamb",
          "500g basmati rice",
          "2 onions, thinly sliced",
          "1/2 cup yogurt",
          "Ginger-garlic paste",
          "Bay leaves, cinnamon, cardamom, cloves, and other biryani spices",
          "Cashews, raisins, and cilantro for garnish",
        ],
        "Indian",
        "biryani.jpg",
      ],
      [
        "Samosa",
        "A popular snack in Indian, Samosas are triangular-shaped pastry pockets that are filled with a variety of savory ingredients like spiced potatoes, peas, onions, and lentils. They are deep-fried until crispy and golden brown and are often served with chutney or a sweet and sour sauce. Samosas are a great snack to munch on and are also served as an appetizer or side dish.",
        "Indian@food.co.vn",
        [
          "2 cups all-purpose flour",
          "1/4 cup vegetable oil",
          "1/2 teaspoon salt",
          "1/2 teaspoon cumin seeds",
          "1/2 teaspoon coriander seeds",
          "2 cups boiled potatoes, mashed",
          "1/2 cup green peas",
          "1/2 teaspoon ginger-garlic paste",
          "2 green chilies, finely chopped",
          "1/2 teaspoon cumin powder",
          "1/2 teaspoon coriander powder",
          "1/4 teaspoon garam masala powder",
          "1/2 teaspoon amchur powder (dried mango powder)",
          "Oil for deep-frying",
        ],
        "Indian",
        "samosa.jpg",
      ],
      [
        "Chole Bhature",
        "Chole Bhature is a popular dish from the northern regions of India. It consists of spicy chickpeas, called chole, and deep-fried bread, called bhature. The chickpeas are cooked with a blend of spices, including ginger, garlic, turmeric, cumin, coriander, and garam masala. Chole Bhature is typically served with a side of pickled vegetables, yogurt, and chutney.",
        "india@food.co.in",
        [
          "Chickpeas",
          "Flour",
          "Yogurt",
          "Ginger",
          "Garlic",
          "Turmeric",
          "Cumin",
          "Coriander",
          "Garam masala",
          "Pickled vegetables",
          "Chutney",
        ],
        "Indian",
        "cholebhature.jpg",
      ],
      [
        "Rogan Josh",
        "Rogan Josh is a flavorful meat dish that originated in the Kashmir region of India. It is typically made with lamb or goat that is slow-cooked in a rich, spicy tomato-based sauce. The sauce is flavored with a blend of aromatic spices, including cinnamon, cardamom, cloves, cumin, coriander, and Kashmiri chili powder. Rogan Josh is often served with rice or naan bread.",
        "india@food.co.in",
        [
          "Lamb or goat meat",
          "Tomatoes",
          "Cinnamon",
          "Cardamom",
          "Cloves",
          "Cumin",
          "Coriander",
          "Kashmiri chili powder",
          "Rice",
          "Naan bread",
        ],
        "Indian",
        "roganjosh.jpg",
      ],
      [
        "Dosa",
        "Dosa is a popular South Indian breakfast food that consists of a thin, crispy pancake made from fermented rice and lentil batter. It is typically served with a spicy potato filling and a variety of chutneys and sambar, a lentil-based vegetable soup. Dosa is a versatile dish that can also be filled with cheese, vegetables, or meat.",
        "india@food.co.in",
        [
          "Rice",
          "Lentils",
          "Potatoes",
          "Chutneys",
          "Sambar",
          "Cheese",
          "Vegetables",
          "Meat",
        ],
        "Indian",
        "dosa.jpg",
      ],
      [
        "Paella",
        "Paella is a classic Spanish dish that originated in the Valencia region of Spain. It is a rice dish that is typically made with a variety of seafood, but can also be made with chicken, rabbit, or vegetables. The rice is seasoned with saffron, garlic, and paprika, and is cooked in a large shallow pan with broth, tomatoes, and other seasonings. Paella is typically served in the pan it was cooked in and is a perfect dish to share with family and friends.",
        "Spanish@food.co.vn",
        [
          "2 cups short-grain rice",
          "1 pound shrimp",
          "1 pound mussels",
          "1 pound chicken or rabbit",
          "1 red bell pepper",
          "1 onion",
          "4 cloves garlic",
          "1 tomato",
          "1 teaspoon paprika",
          "1/2 teaspoon saffron threads",
          "4 cups chicken or vegetable broth",
          "Olive oil",
          "Salt and pepper",
        ],
        "Spanish",
        "paella.jpg",
      ],

      [
        "Gazpacho",
        "Gazpacho is a refreshing and delicious cold soup that originated in the Andalusia region of Spain. It is made with fresh vegetables like tomatoes, cucumbers, peppers, and onions, and is typically served as an appetizer or a light meal on hot summer days. The soup is seasoned with olive oil, vinegar, garlic, and salt, and is often garnished with croutons, chopped vegetables, or herbs. Gazpacho is a perfect way to beat the heat and enjoy the flavors of Spain.",
        "Spanish@food.co.vn",
        [
          "6 ripe tomatoes",
          "1 cucumber",
          "1 red bell pepper",
          "1 small red onion",
          "2 cloves garlic",
          "1/4 cup olive oil",
          "2 tablespoons sherry vinegar",
          "2 cups cold water",
          "Salt and pepper",
          "Croutons and chopped vegetables (optional)",
        ],
        "Spanish",
        "gazpacho.jpg",
      ],
      [
        "Tortilla Española",
        "Tortilla Española is a traditional Spanish omelette made with potatoes, onions, and eggs. It is typically served as a tapa or as a light meal. The omelette can be served warm or at room temperature.",
        "spain@food.co.vn",
        ["Potatoes", "Onions", "Eggs", "Olive oil", "Salt"],
        "Spanish",
        "tortilla.jpg",
      ],
      [
        "Patatas Bravas",
        "Patatas Bravas are fried potato cubes served with a spicy tomato sauce. They are a popular tapa and can be found in many bars and restaurants in Spain. The dish is typically seasoned with paprika and garlic.",
        "spain@food.co.vn",
        [
          "Potatoes",
          "Tomatoes",
          "Olive oil",
          "Paprika",
          "Garlic",
          "Salt",
          "Red pepper",
        ],
        "Spanish",
        "patatasbravas.jpg",
      ],
      [
        "Pollo al ajillo",
        "Pollo al ajillo is a Spanish dish made of chicken cooked with garlic and white wine. The dish is typically served as a main course and is often accompanied by bread or potatoes. The chicken is first browned in olive oil before being simmered with garlic and white wine.",
        "spain@food.co.vn",
        ["Chicken", "Garlic", "White wine", "Olive oil", "Salt", "Pepper"],
        "Spanish",
        "polloalajillo.jpg",
      ],
    ];
    return recipes.map((recipe) => {
      return {
        name: recipe[0],
        description: recipe[1],
        email: recipe[2],
        ingredients: recipe[3],
        category: recipe[4],
        image: recipe[5],
      };
    });
  },
};

module.exports = support;
